/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryItem: typeof import('./src/components/category/CategoryItem.vue')['default']
    ProductGrid: typeof import('./src/components/product/ProductGrid.vue')['default']
    ProductItem: typeof import('./src/components/product/ProductItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
