/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseCheckbox: typeof import('./src/components/base/BaseCheckbox.vue')['default']
    BaseIcon: typeof import('./src/components/base/BaseIcon.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    CartItem: typeof import('./src/components/cart/CartItem.vue')['default']
    CartItemList: typeof import('./src/components/cart/CartItemList.vue')['default']
    CategoryItem: typeof import('./src/components/category/CategoryItem.vue')['default']
    CheckoutForm: typeof import('./src/components/checkout/CheckoutForm.vue')['default']
    EmptyCart: typeof import('./src/components/cart/EmptyCart.vue')['default']
    OrderSummary: typeof import('./src/components/orderSummary/OrderSummary.vue')['default']
    ProductGrid: typeof import('./src/components/product/ProductGrid.vue')['default']
    ProductItem: typeof import('./src/components/product/ProductItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
